### ISSUE TITLE
A log analyzer for api/print3d logs

### ISSUE THREAD

**Issue by woutgg** [Doodle3D/doodle3d-client#116]
Having a log analyzer could make reading logs more productive and effective.
It would have features like collapsing repeated line groups, hyperlinking certain messages (e.g. start/finish/stop printing), etc.
This could be implemented using a php/lua backend and made interacive using js+css. If useful, this could even be integrated into the firmware.

**Comment by olijf** [comment]
Dont have a log analyzer? I believe @woutgg  has scripted this: https://github.com/Doodle3D/doodle3d-firmware/blob/develop/src/script/README-loglite.md

**Comment by peteruithoven** [comment]
Yep.
