### ISSUE TITLE
Support for multiple printers

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-client#157]
**Question**
Is it possible to have multiple printers connected on one box...?!

is the box powerfull enough to send gcode to 2 or more machines

what would be the problems... [technical / interface / speed]

**Awnser**
Basically, we don't know. The reason people always advocate printing from SD card instead of usb is that a regular computer is always distracted with other processes and this shows up as artifacts in your print. In worst cases the printer can even stop for a moment. This might happen on the wifi box when we control multiple printers.
This will basically require some testing.

At the lowest level, the driver (print3d) should be ready, two drivers should start when 2 printers are connected. But this is untested.

One level up (lua) a problem is that with a lot of the api calls you would need to specify the device you want to control. I think there is a foundation for this here and there, but because of time constraints we abandoned proper continuation of this.
There are even some quite fundamental issues, like you probably want some configuration to be printer specific, so that when you change the target printer, the right printer type and temperatures are selected. But with a recent improvement where we made dimensions, heated bed and start- and endgcode printer type specific, this might be quite easy.
Another problem is that we do basic checks, to prevent simple vandalism, you can't update for example when the printer is printing, these checks would need to be expanded to check whether any printer is printing.

On the top level (the Doodle3D webinterface) there is no interface to select a printer, there is basically no multi printer support at all. This would require some ui design. Where and when do we ask what printer the user wants to use and how do we keep this simple enough for people who just use Doodle3D once for 10 minutes.

I think a good place to start is to do some experiments with the lowest level (print3d), there is a command line interface (next to the lua rest api interface), this should allow tests to see if the box can actually handle controlling two printers at the same time.
The following file might be interesting for someone who wants to experiment with this:
https://github.com/Doodle3D/print3d/blob/master/src/frontends/cmdline/fe_cmdline.c
This does require some ssh and other unix command line knowledge.

**Comment by olijf** [comment]
this seems like a wontfix?

**Comment by peteruithoven** [comment]
I agree.
