### ISSUE TITLE
Is a Access point mode button on the WiFi-Box possible?

### ISSUE THREAD

**Issue by BartZuidervaart** [Doodle3D/doodle3d-client#225]
Currently if your WiFi-Box has connected to a WiFi-spot in the past, it will (if it is in client mode) connect to the same WiFi-spot again once it is able to. If you are unable to access the specific WiFi-spot you are unable to access the WiFi-Box.

Currently the only way to access the WiFi-Box in this scenario is to connect to it with the Ethernet cable. Not every user has access to a computer with an Ethernet cable which makes it impossible to access their own WiFi-Box in this scenario.

Is it possible to make the WiFi-Box return to Access point mode if you press and hold the LED-button on the front of the WiFi-Box for approximately 3 seconds? This way every user is able to restore the access to their WiFi-Box without the use of an Ethernet cable. 

![access point mode button](https://f.cloud.github.com/assets/3531528/2383168/c6935188-a8f7-11e3-817d-ec3eaa79474f.jpg)

**Comment by olijf** [comment]
I am currently working on this in https://github.com/Doodle3D/doodle3d-firmware/tree/feature/button-switch-wificonfig although I am planning on using the button to cycle through the different wifi configs

**Comment by companje** [comment]
Since this issue relates to the  https://github.com/Doodle3D/doodle3d-firmware repository I'm closing it here.
