### ISSUE TITLE
Check print/stop parts order

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-client#226]
When someone presses the stop button while still sending print parts it can happen that the stop request arrives at the box before another print part, even though on the client side the order was 1. sending print part and 2. stop. So it seems like requests to the api take longer than others. The fact that print parts requests are bigger might be a reason.
When this happens the printer will perform the stop code and continue with just that last the print part.

To prevent this issue we currently bluntly hide the stop button while sending print parts, see: #35

More backstory: 
https://github.com/Doodle3D/doodle3d-firmware/issues/16

**Comment by peteruithoven** [comment]
@woutgg It's been quite a while, but do you remember why you mention "four mb commands"? Since you ony commented out two comments in the end gcode you added.

**Comment by woutgg** [comment]
I do not remember, but as I understand the issue has now been resolved.
