### ISSUE TITLE
Request 'duplicate' function

### ISSUE THREAD

**Issue by koffiris** [Doodle3D/doodle3d-client#245]
It would be nice to have a 'duplicate function' to be able to print one drawing serval times on the bed at once. So if there is a little counter which you can select an when selecting the plus/minus (normally for resizing your doodle) works temporary as a plus/minus for the number of doodles on your bed it would be nice. But it might be a challenge to print it neat since the way of extrusion from the head should be in a certain way... And maybe program wise it is hard to hook it up to the scaling to be able to know how many doodles max. can be on the bed etc.. But still it would be nice when possible ;-)
![duplicate](https://cloud.githubusercontent.com/assets/2796111/2729379/645865c0-c608-11e3-8cc1-1e80330fd048.png)

**Comment by companje** [comment]
This feature won't be added to the original Doodle3D-client app. However, we have implemented a duplicate/copy-paste function in the next Doodle3D App which is currently in development and will be released soon.
