### ISSUE TITLE
Disable travel-lines

### ISSUE THREAD

**Issue by companje** [Doodle3D/doodle3d-client#265]
![unnamed](https://cloud.githubusercontent.com/assets/156066/5814633/e88faf6e-a08d-11e4-9e59-b47e10c11053.png)

**Comment by companje** [comment]
Duplicate of #270

**Comment by peteruithoven** [comment]
Not really a duplicate if this is issue is for making the traveling on the button lines configurable, instead of just hiding them in the interface.

**Comment by companje** [comment]
I think you can achieve this by changing the following line: https://github.com/Doodle3D/doodle3d-client/blob/master/js/gcodeGenerating.js#L163
by:
```
if (enableTraveling && isTraveling) {
```

**Comment by peteruithoven** [comment]
But then also checking the configuration, whether it's enabled or disabled on the bottom layers right?

**Comment by companje** [comment]
In my opinion the 'travel-lines' are not a feature but more an unwanted behaviour. I know some people like it because it's kind of a poor mans 'raft' because it keeps lose paths connected and helps some printers to stick to the platform. But it was never meant to make it into the release.

**Comment by peteruithoven** [comment]
It's has also proven necessary to get prints to stick on the Wanhao printer, that was the main reason to implement it at that time.

**Comment by companje** [comment]
implemented since 0.10.9. great!
