### ISSUE TITLE
connect page can't get 'update status' from 10.1 wifibox, console shows 404

### ISSUE THREAD

**Issue by companje** [Doodle3D/doodle3d-client#271]
![screen shot 2015-01-22 at 06 08 25](https://cloud.githubusercontent.com/assets/156066/5851279/2e7405b6-a205-11e4-9fca-c3e69bcbb19f.png)

**Comment by companje** [comment]
somehow it tries to call undefined/update/status on the connect website instead of the wifibox.

**Comment by peteruithoven** [comment]
Probably fixed with: 
https://github.com/Doodle3D/doodle3d-connect/commit/ef141ea8594e2ef2db041c7ac13b72d560f03314
