### ISSUE TITLE
WiFi-Box can't connect to network with sign-in

### ISSUE THREAD

**Issue by jeroensomers** [Doodle3D/doodle3d-client#279]
When you connect to a wireless WiFi hotspot with a sign-in you have to go to your browser and must accept terms and conditions to gain access to the Internet. 

But a WiFi-Box doesn't do this, and therefore can't fully connect to the network, and it can't reach the internet. Currently this makes the box inaccessible without a ethernet cable. 
We'll need to research whether we can make the WiFi-box "sign-in" in these kind of networks.

**Comment by olijf** [comment]
As we also did close this issue https://github.com/Doodle3D/doodle3d-firmware/issues/43 can we maybe also close this one?

**Comment by peteruithoven** [comment]
Good one, that makes sense.
