### ISSUE TITLE
Doodle Dream support 

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-client#284]
Because we'd like to make using a Doodle3D Dream with the WiFi-Box as easy as possible, we'd like to postpone adding support until we can automatically adjust the filament thickness per printer type (#162). 
Users can still use the Doodle Dream by using the following settings: 
- Printer type: *Generic Marlin Printer*
- Dimensions: 
  - X: 120
  - Y: 120
  - Z: 80
- Filament thickness: 1.75

**Comment by arneboon** [comment]
Doodle dream implemented nicely including auto filament thickness and usb connect at boot fix. Tested.

See commits:

doodle3d-client: 
https://github.com/Doodle3D/doodle3d-client/commit/38b43e52637bfaaece56f12fc63ed4c33d2100ae

doodle3d-firmware: 
https://github.com/Doodle3D/doodle3d-firmware/commit/d75d1402bc89ed28679edc7f29232c0e516ea83b
https://github.com/Doodle3D/doodle3d-firmware/commit/8318bd265c0b0b07ba32b0118422dae0cfec0fba
https://github.com/Doodle3D/doodle3d-firmware/commit/84f244b8d74deb95cc601701a0f475a177d7daef

print3d:
https://github.com/Doodle3D/print3d/commit/9ebe241e316e0d3eefd74f6b5e753ac4ae676427
https://github.com/Doodle3D/print3d/commit/026c94d745a00b8a3144e79d8265a5dcffe25245
