### ISSUE TITLE
Can the WiFi-Box connect to 5GHz networks?

### ISSUE THREAD

**Issue by companje** [Doodle3D/doodle3d-client#297]

**Comment by woutgg** [comment]
According to [their own specs](http://www.tp-link.com/en/products/details/cat-4691_TL-MR3020.html#specifications) it does not.
Although it is a b/g/n-capable device and the 802.11n standard supports the 5GHz band, apparently that does not mean devices can actually use it (according to various sources).

**Comment by olijf** [comment]
see @woutgg 's comment
