### ISSUE TITLE
Can we add support for external USB flash drives?

### ISSUE THREAD

**Issue by companje** [Doodle3D/doodle3d-client#64]
This would be very useful because it gives you a lot more space for caching, importing and exporting large files like STL's, GCODE, bitmaps, SVG's etc.

**Comment by olijf** [comment]
See https://github.com/Doodle3D/WiFi-Box/issues/8 for possibilities

**Comment by peteruithoven** [comment]
I'm regarding this one outdated in favor of https://github.com/Doodle3D/WiFi-Box/issues/8
