### ISSUE TITLE
Debug: Make it easier to increase amount of logging (for debugging)

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/doodle3d-client#67]
To debug most of the printer communication issues we need a higher logging level. We can't enable this high level by default because it logs so much the logs fill all the space on the box and crash the box after a while. 
So maybe we need a checkbox in the Debug section of the settings to increase logging. Something like "Enable extra logs (for debugging purposes only)". 

Implementing this means we can ask a user to increase the logging and then to reproduce the issue. Then users can send us more useful logs.

**Comment by woutgg** [comment]
Note: the file debug.html does not exist anymore, setting log levels is now included in the settings dialog.
