### ISSUE TITLE
Sprinter firmware: Does not print.

### ISSUE THREAD

**Issue by NightOwl01** [Doodle3D/doodle3d-client#73]
I have a Vision printer which is a Prusa-Mendel using a Mega-RAMPS 1.4 controller and Sprinter.  I have the system hooked up as it shows on the box, even in that order.  I can connect to the WiFi box with my Nexus 7 and draw an image, but when I press the Print button nothing happens.  A popup window says that it is sending the doodle to the printer and the picture of the thermometer shows up.  The Print button greys out and the red stop button highlights.  Then the popup says the doodle was sent to the printer, the print button highlights and the stop button greys out.  
The LEDs on the RAMPS for the heated bed and hot end do not light up.  In settings I changed it to say that my printer was a Vision 3D printer.  
Is there a way to test to see if it connecting to the printer?

**Comment by olijf** [comment]
Has this issue been looked into? Smells like the craftbot issue we had recently...

**Comment by companje** [comment]
Since this is a old issue which has not been active for quite a while I'm closing this now. Feel free to re-open when appropriate.
