### ISSUE TITLE
Printer starts creeping in middle of print - Repetier FW

### ISSUE THREAD

**Issue by bieshaar** [Doodle3D/doodle3d-client#93]
When a doodle is printing, suddenly the printer starts creeping along the path.
In other words, the printer continues to print the doodle but at very very low speed.
Comm. Issue? Baudrate = 115200, FW = Repetier

**Comment by woutgg** [comment]
This might have had to do with gcode->s3g conversion, which is done in a less taxing way now. Instead of converting all gcode as soon as it is received, it is now converted only just before sending it to the printer.

**Comment by companje** [comment]
I think we can close this issue from 2013. The Mamba3D printer with Repetier firmware works well these days.
